/* --------------------------------- imports -------------------------------- */

/* ------------------------------ constants ----------------------------- */
export const solarBarText =
  "China continues its dominance with solar energy production. The eastern superpower beats out the remaining top 9 countries by over 8,000 MW. Out of the top three countries, two are Asian. The United States places second but still severely lacking as it is almost 1/3 of the megawatts generated by China.";

export const windBarText =
  "We see that China is a massive leader in the wind energy race. The top 9 countries combined have only generated 12,000 MW (megawatts) more than their Asian counterpart. China continues its dominance with solar energy production. The eastern superpower beats out the remaining top 9 countries by over 8,000 MW. ";

export const solarLineText=
"Here we see China’s dominance over a 10-year period but also the United States consistency. The United States was the first country to implement solar energy and consistently did it over a 13-year period, albeit not on the level of China. This graph reflects the dominance of Asian countries as Vietnam, China and India are all in the top four."

export const windLineText=
"This graph shows that the United States was first to implement and China continuing its dominating path. It also shows that there must be wind energy initiatives in place as countries from Europe, Asia and North America are all in the top five. One interesting aspect of the graph is although China is dominating the space, they were the latest adopter."
  /* --------------------------------- exports -------------------------------- */
